### ISSUE TITLE
the process for add new node?

### ISSUE THREAD

**Issue by robertiko07** [nRF24/RF24Mesh#102]
hi friend TMRh20
i try make a similar network/mesh as you.
but i want use PIC microcontroller.. my problem consist over addressing new node

can you make a image for explain, the protocole that need follow a new node to request new address  heself?

can you tell us the strategies for it?

the theory is that the new node look for some parent.. 
but how know a new node, the parent address if its no in the network parent?

**Comment by Avamander** [comment]
I think the easiest way for you is to read the source code if you wish to port the library for PIC MCs.
