### ISSUE TITLE
Address 0100 and 070 in the library code

### ISSUE THREAD

**Issue by phuckhoi2494** [nRF24/RF24Mesh#106]
Hi everyone, I'm trying to learn the algorithm from the library of TMRh20. In this code below:

```
bool RF24Network::multicast(RF24NetworkHeader& header,const void* message, uint16_t len, uint8_t level){
	// Fill out the header
  header.to_node = 0100;
  header.from_node = node_address;
  return write(header, message, len, levelToAddress(level));
}
#endif

/******************************************************************/
bool RF24Network::write(RF24NetworkHeader& header,const void* message, uint16_t len){    
	return write(header,message,len,070); 
```

I see the addresses 0100 and 070. I only know (00, 01, 011, 0111) is a branch on "tree topology", I've never seen 0100. Could you please explain the "0100" and why they use "0100" and "070" in the code ?
Thank you very much

**Comment by TMRh20** [comment]
0100 means it is a multicast message, addressed to all nodes
070 is just a default in the code, so the network layer knows it is a standard message
