### ISSUE TITLE
Python Wrapper

### ISSUE THREAD

**Issue by joernesdohr** [nRF24/RF24Mesh#108]
I made a boost python wrapper for RF24Mesh and don't want to keep it from you: https://github.com/joernesdohr/RF24Mesh/tree/master/pyRF24Mesh

I haven't done extensive testing, but communication between a RPi master and Arduino node was working as expected. The wrapper could be pulled into the main repo after review.

**Comment by Avamander** [comment]
RF24 also has a Python wrapper, have you thought about pushing your wrapper into this repository and including everything necessary to get it working (with examples)?

**Comment by filipek92** [comment]
Thank you @joernesdohr for your work on wrapper
