### ISSUE TITLE
Radio PowerAmplification level. (Message arrives but mesh.write() returns false.)

### ISSUE THREAD

**Issue by adamdabrowski04** [nRF24/RF24Mesh#114]
When testing my system I was getting frames but write() was returning false( it wasn't getting ACK frame). The solution was to turn down radio PA level. During normal operation nodes won't be as close to eacho other as they are now(during testing). Is there a good way to set Radio PA levels automatically ?

**Comment by Avamander** [comment]
The library does not have built-in method to do so, but you can always do
some magic retrying with different PA levels.
