### ISSUE TITLE
Client sending data twice & it shows "Send fail, Test OK"

### ISSUE THREAD

**Issue by dnksavaliya** [nRF24/RF24Mesh#127]
Hello sir,

Is their any algorithm available for dynamic mesh network send fail detection & resend data ?

When trying logic below it sometimes send data twice ...

if (!mesh.write(&payload, 'M', sizeof(payload))) {
if ( ! mesh.checkConnection() ) {
Serial.println("Renewing Address");
mesh.renewAddress();
} else {
Serial.println("Send fail, Test OK");
delay(500);
mesh.write(&payload, 'M', sizeof(payload));
radio.enableAckPayload();
radio.enableDynamicPayloads();
}
} else {
Serial.print("Send OK: ");
}

**Comment by TMRh20** [comment]
Not by default, no
