### ISSUE TITLE
Addresses Allocation Problem

### ISSUE THREAD

**Issue by Kevinleaf** [nRF24/RF24Mesh#128]
When I restart my master node, I have 15 nodes trying to renew their address. There is always 5-6 nodes getting addresses which aren't in the master node address list for some reason...

If I reconnect all my nodes one by one, it will be fine.

**Comment by Avamander** [comment]
Read the first part of your sentence again. Node was already assigned an address, until you make the node ask a new address it's gonna keep using it old one thinking it's legit, it has no built-in and fast way to check.
