### ISSUE TITLE
ESP8266 Reset With "Rf24Mesh_Example"

### ISSUE THREAD

**Issue by TienHuyIoT** [nRF24/RF24Mesh#129]
I had tested OK  "Rf24Mesh_Example" with Arduino Uno. But when I try with Esp8266 is not OK. Esp8266 reset. How to fix bug please!
If I try "Rf24Mesh_Example_Master" is OK.

Connecting to the mesh...
Exception (3):
epc1=0x40202124 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40230af0 depc=0x00000000

ctx: cont 
sp: 3ffef3e0 end: 3ffef610 offset: 01a0

>>>stack>>>
3ffef580:  00000000 00000003 3ffee4bc 4020211f  
3ffef590:  00000006 3ffee4bc 3ffee30c 40203a00  
3ffef5a0:  00000006 3ffee4bc 3ffee4dc 40201e38  
3ffef5b0:  00000000 3ffee4bc 00000007 0000ea60  
3ffef5c0:  3ffee334 00000003 3ffee30c 40203ad4  
3ffef5d0:  3fffdad0 3ffee5b8 3ffee5b8 3ffee5dc  
3ffef5e0:  3fffdad0 3ffee5b8 3ffee30c 40201c2c  
3ffef5f0:  feefeffe 00000000 3ffee5d4 402041e8  
3ffef600:  feefeffe feefeffe 3ffee5f0 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

**Comment by Avamander** [comment]
Update your NodeMCU.
