### ISSUE TITLE
Max Bandwidth?

### ISSUE THREAD

**Issue by Rotario** [nRF24/RF24Mesh#130]
Hi,
I'm looking at applying this to increase the number of senders I can link to one receiver (ie 10, greater than the six maximum addresses on one receiving chip).

I would be looking at 10 senders and one receiver in the mesh network.
The problem is the bandwidth required at the moment is around 12kbps and is only going to increase in the future. Would this mesh system be capable of relaying 10 x 12kbps to one receiver?

Many thanks in advance,
Rowan

**Comment by Avamander** [comment]
With 10 senders, you have to have at least three repeaters, you'll possibly end up with more. You have to test what's the bandwidth you'll get in your specific environment, because noise and etc. play a part here too, 12kbps should be theoretically manageable, but you simply have to test it.
