### ISSUE TITLE
Send a message to a speccific node in a NRF24mesh 

### ISSUE THREAD

**Issue by EliiMo** [nRF24/RF24Mesh#133]
Hi
I´ve been working with RF24Mesh but I don´t know how to send a message to a specific node in the mesh.

**Comment by Exormeter** [comment]
Use the `mesh.write(const void *data, uint8_t msg_type, size_t size, uint8_t nodeID=0)` 
function to send a message to a specific node. The last parameter should be the the nodeID which is the recipient. This parameter is optional and if the parameter is missing, the master node is automatically the recipient.
