### ISSUE TITLE
Connecting slave to specific master [question]

### ISSUE THREAD

**Issue by mitko9000** [nRF24/RF24Mesh#134]
Hello is it possible to connect slave to specific master let say scenario slaveOne needs to connect with masterOne and slaveTwo needs to connect with masterTwo and they are in the say room, can anyone throw some light how this can happend ?

Are masters adresses limited from 0 - 255 can it be something unique like tr[node_adress_here]Two123 ?

**Comment by Avamander** [comment]
Use a different channel.

**Comment by mitko9000** [comment]
@Avamander Is it possible to detect if current channel is busy ?

**Comment by Avamander** [comment]
Yes, manually listen on the pipes that are used by the masters and see if there's communication.
