### ISSUE TITLE
Does RF24Mesh work with RF24Audio?

### ISSUE THREAD

**Issue by SimonMerrett** [nRF24/RF24Mesh#136]
The title says it all really. I'd like to make walkie talkies from NRF24L01+ PA LNAs, such as in this [Instructable](http://www.instructables.com/id/Wristwatch-Walkie-Talkie/). Mesh would be lovely. Please let me know if there's anything else I can say to help you reply/advise.

**Comment by TMRh20** [comment]
Nope, with AAAudio library, audio relays can be manually configured to extend range, but it’s separate from RF24Mesh

**Comment by SimonMerrett** [comment]
Thanks for your reply.
