### ISSUE TITLE
Changing the MESH_DEFAULT_ADDRESS in RF24Mesh_config.h fails

### ISSUE THREAD

**Issue by MAKOMO** [nRF24/RF24Mesh#140]
Changing the MESH_DEFAULT_ADDRESS in RF24Mesh_config.h fails, as in RF24Network.cpp the network default address is hardcoded in two places. This can be resolved easily by introducing a NETWORK_DEFAULT_ADDRESSin RF24Network (see pulls the following pulls https://github.com/nRF24/RF24Network/pull/116 and https://github.com/nRF24/RF24Mesh/pull/139)

**Comment by TMRh20** [comment]
Thank for the PRs, they have been merged.
