### ISSUE TITLE
Fragmented Message from Raspberry to Arduino not working

### ISSUE THREAD

**Issue by edusacchi** [nRF24/RF24Mesh#143]
Hi,
First sorry about my english. I'll try to show you my problem.
I'm trying to send a fragmented message from a Rapsberry Pi 3 to a Arduino Mega and this isn't working as expected. I turned on the debug flags e added some prints to show me what is happening. After receive the first fragment the network seems to stop receiving the next fragments. I don't know if this is a RF24Mesh or RF24Network problem.
Has someone get this problem? 
Anybody?
Thanks

**Comment by TMRh20** [comment]
This likely has something to do with RF24Network, as that is where the fragmentation/reassembly takes place. Are you using the latest RF24Network from Arduino Library manager? Could you provided simplified example code that demonstrates this problem?
