### ISSUE TITLE
rf24 mesh networking problem

### ISSUE THREAD

**Issue by ashok-singamreddy** [nRF24/RF24Mesh#148]
Hi all,
Hardware used:
Ardunio Uno and a nrf24l01 at each node including master, at the client some sensors and switches were used.
I am using rf24 mesh networking with one master and many clients. Here i am using 3 clients, 2 are sending data to the master and one is receiving data from the master. If am trying to add one more node to send data to the master that time, the data reception at becoming random. I mean some nodes are failed to send data at some times. The node supposed to send data serially one by one to the master but randomly it is receiving. This problem was coming if i am trying to connect more than 3 client nodes.

Kindly waiting for the replay.

**Comment by TMRh20** [comment]
Sounds like an interference problem. Changing the default channel with ` mesh.begin(channelNo); ` may increase performance.
