### ISSUE TITLE
Can I stuff this library into Atmega8?

### ISSUE THREAD

**Issue by positron96** [nRF24/RF24Mesh#149]
The compiled example for arduino (atmega328) is around 10k, is there a way to reduce it to under 8k?

**Comment by TMRh20** [comment]
It typically compiles smaller on smaller devices, but it will be close.

**Comment by Avamander** [comment]
Exclude the strings, enable LTO, then it'll probably barely fit.

**Comment by positron96** [comment]
Yes, it did. It also required to update arduino avr compiler to a new one.
