### ISSUE TITLE
Question : one master and two slave with mesh

### ISSUE THREAD

**Issue by Russell19990913** [nRF24/RF24Mesh#150]
Hello
I have two slaves and one master and i want to send data from one of the slaves to another one then master .
when i test the mesh example and change distance master didn't receive data from the slave that distance too far . now what should i do ? please help ...

![picture](https://user-images.githubusercontent.com/43312553/45595057-e7dee400-b9ba-11e8-93ab-f9082a48453c.png)

**Comment by TMRh20** [comment]
Reduce the distance between slaves. If there are still problems with communication, try using a different radio channel when you start up the mesh. https://tmrh20.github.io/RF24Mesh/classRF24Mesh.html#a4159edcb2a13c713cd9c524315270902
