### ISSUE TITLE
Conflict during unicast write?

### ISSUE THREAD

**Issue by Zuputmer** [nRF24/RF24Mesh#159]
Hi, i have a question. I am using unicast write to send data to a mesh master from a number of battery powered nodes. If more than one node sends data to the master using unicast write at the same time, will a collision or a conflict occur in the network? If so, is there any way to resolve the situation?

Also, when a master receives data that the slave has sent using unicast write, will the IRQ pin on the master go high?

Any help would be greatly appreciated. Thanks in advance.

**Comment by TMRh20** [comment]
Collisions can’t really be avoided or mitigated using unicast.

The IRQ pin is active low.

**Comment by Zuputmer** [comment]
@TMRh20 thank you
