### ISSUE TITLE
Question: mesh with wired and wireless nodes

### ISSUE THREAD

**Issue by prof-rt** [nRF24/RF24Mesh#162]
Hi,

I'm planning a sensor network that will span a 3 storey building.  I have concerns re spanning the 2nd floor, in that the distance between the 3rd floor sensors and 1st floor sensors will not have  a connecting node in between.  However there is a wired connection between the third floor and the first floor, and i can use rpi nodes at either end.  is there anyway to get a wired connection between a third floor rpi slave node and the first floor rpi master node to work in the mesh?

Any pointers in the right direction would be appreciated.

R

**Comment by TMRh20** [comment]
I think the only way to link them by wire would be to wire the RPis together and have two separate networks. Else you could try using a couple higher powered modules with antennae to create a link between floors.
