### ISSUE TITLE
Temporarily Unlinking a node

### ISSUE THREAD

**Issue by itisyeetimetoday** [nRF24/RF24Mesh#168]
Hi,
Is it possible to use this library for transmitting telemetry data, then using this library to send out a packet of information, like telling the module to become a repeater? After that, is it still possible to have the node rejoin the network?

**Comment by TMRh20** [comment]
Umm, yes?

**Comment by TMRh20** [comment]
No example, but the only way to have 2 separate master nodes is to start them up on separate channels. Then the node(s) can just switch channels to switch between masters.

**Comment by itisyeetimetoday** [comment]
Thank you! However, is there a way to send a message from the master to the slave?
