### ISSUE TITLE
deploy documentation using Github Pages

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Mesh#176]
This issue is part of an effort to start hosting nRF24 org repos' docs on github per individual repo instead of uploading all RF24* lib's docs to tmrh20.github.io.

I've created a github workflow that builds the docs on every commit. This same workflow will upload the generated HTML files to the "gh-pages" branch upon publishing a new release. Notice I've already taken the liberty to create the "gh-pages" branch for this repo.

1. For this workflow to work properly, this repo's settings needs to have the "gh-pages" branch set to the Github Pages Source option:
![image](https://user-images.githubusercontent.com/14963867/100502583-d22fe200-3120-11eb-89aa-f2eb2e936f8d.png)
    After enabling this option, I expect the first deployment to Github Pages to render an error message.

2. Additionally, it would less visually noisy if the "packages" & "environments" sections are hidden in the repo's sidebar settings:
![image](https://user-images.githubusercontent.com/14963867/100505379-9c3f2d80-3121-11eb-91f3-b03cd746e1d9.png)

When these stipulations have been met in the repo settings I will submit a PR

**Comment by Avamander** [comment]
Done
