### ISSUE TITLE
Issue:  DHCP() function Not recognize in Arduino code.

### ISSUE THREAD

**Issue by lak1219** [nRF24/RF24Mesh#182]
Hi,
Anyone can help me?
Calling DHCP() function doesn't work in my Arduino code.  I didn't see the function name orange colour after I checked the code. 

Where is the problem?

Thank you...

![DHCP](https://user-images.githubusercontent.com/81774193/113341798-3f5fb800-934b-11eb-829f-1d4e9c748be1.JPG)

**Comment by TMRh20** [comment]
Not sure what isn’t working, it doesn’t matter if it’s orange in the ide. Make sure to test your devices with the basic rf24 examples before using RF24Mesh.

**Comment by lak1219** [comment]
Thanks for your response.
Already Basicrf24 and also Rf24mesh working. But the problem is in the DHCP() Function.  I want to call DHCP() function at a specific time because I am going to implement sleep mode to reduce the power consumption of my sensor nodes.
