### ISSUE TITLE
Unable to set Radio Power is not changing -- a Bug methinks

### ISSUE THREAD

**Issue by FlailAway** [nRF24/RF24Mesh#187]
SORRY ABOUT THE FORMATTING I AM USING LINUX AND THIS KEEPS DROPPING THE FORMAT AS I EDIT. Probably expecting a CR+LF and we only use LF.  AND, I can't seem t delete it all to start again.

I quit.

**Comment by 2bndy5** [comment]
??? you can re-open this if you still have this problem. Generally we need **_way more detail_** to try and diagnose a problem that we can't reproduce.
