### ISSUE TITLE
waitForAvailable() has no definition

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Mesh#195]
I noticed that there is a private function named `waitForAvailable()` that's [declared in _RF24Mesh.h_](https://github.com/nRF24/RF24Mesh/blob/aa5422bed7302a3148afa7891a097a92d25c363a/RF24Mesh.h#L290), but the [definition has been commented out](https://github.com/nRF24/RF24Mesh/blob/aa5422bed7302a3148afa7891a097a92d25c363a/RF24Mesh.cpp#L439-L450) in _RF24Mesh.cpp_. [git blames this commit](https://github.com/nRF24/RF24Mesh/commit/360f8a1196601abddfb9a6338c15804a8bb85212), but there is no explicit justification. It looks like it was used instead of `RF24Network::update()` (but with a timeout parameter) when developing `releaseAddress()`.

**Comment by TMRh20** [comment]
I think that was experimental in nature and can safely be removed/forgotten.
