### ISSUE TITLE
Is there a use case for a changing master node?

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Mesh#206]
I was testing the exposed `addrList` in pyrf24 and hit a segmentation fault when I changed the mesh child node into a master node and explicitly called `loadDHCP()`. I already can see the problem because if the node's ID is not 0 upon calling `mesh.begin()`, then the `addrList` doesn't have any memory allocated.
<details><summary>code to reproduce segmentation fault</summary>

```cpp
mesh.setNodeID(1);
mesh.begin();
mesh.setNodeID(0);
mesh.renewAddress();
mesh.loadDHCP();
```
</details>

Is there a practical use case in which the master node of a mesh can change similar to how child nodes change?

This wouldn't be a hard problem to solve, but it would definitely involve increased compile size... One could probably just solve it by recalling `mesh.begin()` after `mesh.setNodeID(0)`.

**Comment by TMRh20** [comment]
I don't think there is really a use case for it, plus as you mentioned it would increase memory and program space usage just to support an unlikely scenario.

**Comment by 2bndy5** [comment]
I also had an idea a while back (when porting to pure python) to reserve a msg type that transfers the DHCP list to a new master node. The only case for that would be if you want a continuous network running while phasing in a firmware update.
