### ISSUE TITLE
2 master slave systems in one room

### ISSUE THREAD

**Issue by Chris-656** [nRF24/RF24Mesh#233]
Is there a possibility to use 2 or even more mesh systems with 1 Master and 3 slaves, so that the 2 different meshes can work without disturbing each other ?
thx Chris

**Comment by Chris-656** [comment]
When you are using 2 mesh Networks independently in one room.
Do they interferre each other ?

Do the slaves of system 1 only send to master 1.

Regards Chris

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 2bndy5** [comment]
Also look at the [`mesh.begin()`](https://nrf24.github.io/RF24Mesh/classESBMesh.html#a44cf6f2b41525b2bc4ba1750364fd8b8). You can easily set the channel for a mesh network using that function. Remember, **each mesh network must have a unique channel**, and all nodes in a single mesh network must use the same channel as the master node.

**Comment by Chris-656** [comment]
Thx so it is possible
Regards Chris

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
