### ISSUE TITLE
Missing node will disable all children.

### ISSUE THREAD

**Issue by JonasZaverka** [nRF24/RF24Mesh#237]
Hi, Im trying to implement this awesome library into my bachelor thesis.
I ran into an issue.
![Picture1](https://github.com/nRF24/RF24Mesh/assets/26128039/e6fb5dbb-64b8-4ab2-9e7b-d6c1feb9342f)
In this picture all is working fine.
Now I’m going to disable nodID:4 
![Picture2](https://github.com/nRF24/RF24Mesh/assets/26128039/906147d7-c225-4681-9e3b-fa1624c8216a)
Children of nodeID:4 will not get a valid address. 
All comunication fails. mesh.renewAddress() and mesh.begin(); doesnt help. 

This persist until nodeID:4 is back online. 

After nodeID:4 is back online. After some time, all is working fine.
![Picture3](https://github.com/nRF24/RF24Mesh/assets/26128039/4640633a-2db6-46fa-addc-80d9e5d6bad4)

But for me it’s quite a problem since losing a node is not an unrealistic problem.
Is this issue with my code or setup.
Or perhaps this scenario will not work? 

Thank you, i can send code if anybody suggests that this should work fine but my code is at fault :) 

Thank you very much for your work.

**Comment by TMRh20** [comment]
Nodes need to verify their connection periodically. If you look at the examples, you will see exactly this.

I have my nodes checking their connection every 30 seconds, while the example verifies the connection whenever a write fails.

**Comment by JonasZaverka** [comment]
if i dont verify the connection nothing happens. After i try sending something it fails and tries to reconnect. That it gets this weird address.  Honestly i ran into memory issues a little later. It may be that. But if i understood correctly.  If one of the nodes goes missing the library should handle reassigning new addresses to all of the missing nodes children. Is that correct ?

**Comment by 2bndy5** [comment]
>  If one of the nodes goes missing the library should handle reassigning new addresses to all of the missing nodes children. Is that correct ?

The correct answer is no because you have to implement the connectivity handling in user code. See any of the examples and look at where [`renewAddress()`](https://nrf24.github.io/RF24Mesh/classESBMesh.html#a234862c9d9729b3ca11fcb9b29ec55b1) is used.
https://github.com/nRF24/RF24Mesh/blob/7c30debee4b91d63c27847213eaf10d413a10212/examples/RF24Mesh_Example/RF24Mesh_Example.ino#L83-L91
