### ISSUE TITLE
Support for NRF24LE1 or NRF24LU1+.

### ISSUE THREAD

**Issue by rajithavk** [nRF24/RF24Mesh#96]
Can this stack be built for NRF24LE1 or NRF24LU1+ ? Both these SoC's have included their own  MCU. If this Mesh stack can be used on them, it's going to be one powerful module since no other MCUs are needed.

**Comment by TMRh20** [comment]
It almost certainly could be.

The radio API seems to be much the same as 24L01+ , so I assume it would be a matter of adapting the core RF24 driver via the [portability template](http://tmrh20.github.io/RF24/Portability.html) or if there is an Arduino core available, it would just work.

Above that, there should be no other dependencies.

**Comment by rajithavk** [comment]
Great, I didn't know about the portability template. Thanks a lot 👍.
BTW, my real requirement is a sensor network so, that time synchronization is very critical. Does the current implementation has built in time synchronization mechanism? or will i have to work on it?
Thank you.

**Comment by TMRh20** [comment]
Nothing really built in regarding time sync. Nodes can be set up to request the time from a single device with RTC capabilities via standard communication, as in the RF24Gateway examples.
