### ISSUE TITLE
Delete a nodeID from the mesh list

### ISSUE THREAD

**Issue by ricmail85** [nRF24/RF24Mesh#98]
Dear TMRh20,
I was wondering if there is the possibility with your fantastic library to delete a specific nodeID from the mesh list. For example, if by pinging a nodeID for a certain time there is no reply, my code would delete it from the mesh list, avoiding to wait for its reply in future.

I know I can set the address to 00, but the node is still in the mesh list...

What do you think?
Thanks!

bye.

**Comment by TMRh20** [comment]
The code to delete a node from the list will be more complicated, because the list needs to be re-organized each time. For simplicity this has been left out, but for use with larger devices like RPi etc, it may be a better option.
